<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_entity_info_alter().
 */
function scout_inline_forms_entity_info_alter(&$entity_info) {

  if (isset($entity_info['scout_tip'])) {
    $entity_info['scout_tip']['inline entity form'] = array(
      'controller' => 'ScoutInlineEntityFormController',
    );
  }

  if (isset($entity_info['scout_trail'])) {
    $entity_info['scout_trail']['inline entity form'] = array(
      'controller' => 'EntityInlineEntityFormController',
    );
  }
}
